### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ldejager** [discordianfish/banksman#2]
Hi Johannes,

I’d like to use banksman to provide the interface between ipxe and collins, could you indicate what licensing applies to the project?

Thanks!

**Comment by discordianfish** [comment]
Good catch! :)
I've added apache 2 license.

Be warned though: I haven't touched this for a while and have no bare metal infra to attend to anymore. That being said, it's pretty straight forward code so if you run into issue it should be fairly easy to fix them.
